version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: ./backend # Path to your app
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=${PORT}
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads/
      - ./backend/src:/app/src # Path to your app source code



  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=husirxd@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test123#
    ports:
      - '5050:80'
    depends_on:
      - db

