version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: ./backend # Path to your app
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src

  frontend: 
    build:
      context: ./frontend # Path to your Next.js app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3001:3000'


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=husirxd@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test123#
    ports:
      - '5050:80'
    depends_on:
      - db